### ISSUE TITLE
多行文本溢出，超出两行（n 行）溢出省略号

### ISSUE THREAD

**Issue by nanhupatar** [re-learning-front-end/fe-tricks#2]
```scss
@mixin textOverflow($line: 1) {
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  /*! autoprefixer: off */
  -webkit-box-orient: vertical;
  -webkit-line-clamp: $line;
}
```

简单示例

超出两行溢出
```css
.textOverflow2() {
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  /*! autoprefixer: off */
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 2;
}
```
