### ISSUE TITLE
css文字两端居中

### ISSUE THREAD

**Issue by nanhupatar** [re-learning-front-end/fe-tricks#3]
此方案为司徒正美方案

```css
.test1 {
  text-align: justify;
  text-justify: distribute-all-lines; /*ie6-8*/
  text-align-last: justify; /* ie9*/
  -moz-text-align-last: justify; /*ff*/
  -webkit-text-align-last: justify; /*chrome 20+*/
}

@media screen and (-webkit-min-device-pixel-ratio: 0) {
  /* chrome*/
  .test1:after {
    content: ".";
    display: inline-block;
    width: 100%;
    overflow: hidden;
    height: 0;
  }
}
```
