### ISSUE TITLE
window.print()打印背景色

### ISSUE THREAD

**Issue by nanhupatar** [re-learning-front-end/fe-tricks#5]
```css
<style type="text/css">
@media print {
  body {-webkit-print-color-adjust: exact;}
}
</style>
```
